openapi: 3.0.1
info:
  title: TODO Plugin
  description: A plugin that queries the On-Line Encyclopedia of Integer Sequences (OEIS) to complete the input of the user when the input includes an integer sequence.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /process/{message}:
    get:
      operationId: getIntegerSequenceInfo
      summary: Get information about the integer sequence
      parameters:
      - in: path
        name: message
        schema:
            type: string
        required: true
        description: The potential integer sequence
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getIntegerSequenceInfo'

components:
  schemas:
    getIntegerSequenceInfo:
      type: object
      properties:
        name:
          type: string
          description: Name of the integer sequence input by the user.
        data:
          type: string
          description: Completion of the sequence input by the user.